### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by marcoafsilva** [microvb/otp-thing#3]
I'm getting an error before install it.
The error is:
Parse error: syntax error, unexpected '*', expecting ',' or ';' in /home/ubuntu/workspace/app/lib/session.class.php on line 21 Call Stack: 0.0016 238920 1. {main}() /home/ubuntu/workspace/app/controller.php:0 0.0020 240400 2. require_once('/home/ubuntu/workspace/app/lib/autoload.php') /home/ubuntu/workspace/app/controller.php:3

**Comment by dkrusky** [comment]
What version of PHP are you running ?   The line you are referencing is valid PHP but earlier editions of PHP do not support defining `static` variables inside a class.

In any case, you can try changing line 21 in `/app/lib/session.class.php` to `var $duration = 123456;` where `123456` is the number of milliseconds you wish to set for session expiration.
